{"name": "test_get_pet", "status": "failed", "statusDetails": {"message": "AssertionError: assert 404 == 200\n +  where 404 = <Response [404]>.status_code", "trace": "def test_get_pet():\n        path = \"v2/pet/1989\"\n        response = requests.get(url=baseUrl + path)\n        response_json = json.loads(response.text)\n        logging.info(f'Get method is called')\n        logging.info(f'Response: {response.text}')\n>       assert response.status_code == 200\nE       assert 404 == 200\nE        +  where 404 = <Response [404]>.status_code\n\ntests\\test_pets.py:28: AssertionError"}, "attachments": [{"name": "log", "source": "aaafc8a9-9bc0-468c-a337-bbaab7d8a472-attachment.txt", "type": "text/plain"}], "start": 1658400320581, "stop": 1658400321261, "uuid": "8cc0172d-c54b-40c5-ac77-62f0380ef52a", "historyId": "46d9161bf09a7314e1831203588114c3", "testCaseId": "b9ece5fee8ff47f96a501991df73077f", "fullName": "tests.test_pets#test_get_pet", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_pets"}, {"name": "host", "value": "A00639991A"}, {"name": "thread", "value": "31176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_pets"}]}